version: "3.7"

services:
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    restart: always
  blog:
    build: ./blog
    volumes:
      - ./blog:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3000
    tty: true
    restart: always
  api:
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=erys
      - DATABASE_USERNAME=erys
      - DATABASE_PASSWORD=erys
    volumes:
      - ./api:/srv/app
    ports:
      - 1337:1337
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: erys
      MYSQL_USER: erys
      MYSQL_PASSWORD: erys
      MYSQL_ROOT_PASSWORD: erys
    volumes:
      - ./data:/var/lib/mysql
      - ./db/mysql.cnf:/etc/mysql/conf.d/custom.cnf
