version: "3.7"

services:
  api:
    image: strapi/strapi
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=erys
      - DATABASE_USERNAME=erys
      - DATABASE_PASSWORD=erys
      - DATABASE_CHARSET=utf8mb4_unicode_ci
    volumes:
      - ./api:/srv/app
    ports:
      - 8008:1337
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: erys
      MYSQL_USER: erys
      MYSQL_PASSWORD: erys
      MYSQL_ROOT_PASSWORD: erys
    volumes:
      - ./data:/var/lib/mysql
      - ./db/mysql.cnf:/etc/mysql/conf.d/custom.cnf
