version: "3.7"

services:
  api:
    image: strapi/strapi
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=erys
      - DATABASE_USERNAME=erys
      - DATABASE_PASSWORD=erys
    volumes:
      - ./api:/srv/app
    ports:
      - 8008:1337
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: erys
      MYSQL_USER: erys
      MYSQL_PASSWORD: erys
      MYSQL_ROOT_PASSWORD: erys
    volumes:
      - ./db:/var/lib/mysql
